name: SocialBridge-telegram
version: '0.5.3'
main: io.github.kosyakmakc.socialBridgeTelegram.paper.SocialBridgeTelegramPlugin
api-version: '1.21'
authors: [ kosyakmakc ]
depend: [ SocialBridge ]
folia-supported: true