name: SocialBridge-telegram
version: '0.6.0'
main: io.github.kosyakmakc.socialBridgeTelegram.paper.SocialBridgeTelegramPlugin
api-version: '1.21'
authors: [ kosyakmakc ]
depend: [ SocialBridge ]
folia-supported: true